---
# Mode: 'audit' (report-only) or 'enforce' (make changes)
cis_mode: audit

# Baseline packages required for this role
cis_packages:
  - libpam-pwquality
  - auditd
  - ufw
  - rsyslog
  - unattended-upgrades

# Password aging values for /etc/login.defs
cis_password_aging:
  PASS_MAX_DAYS: 90
  PASS_MIN_DAYS: 1
  PASS_WARN_AGE: 7

# pwquality minimums (/etc/security/pwquality.conf)
cis_pwquality:
  minlen: 12
  dcredit: -1
  ucredit: -1
  lcredit: -1
  ocredit: -1
  retry: 3

# SSH hardening
cis_ssh_port: 22
cis_sshd_dropin_path: /etc/ssh/sshd_config.d/10-ansible.conf
