---
- name: Include package tasks
  ansible.builtin.import_tasks: packages.yml
  tags: [packages]

- name: Include auth (login.defs + pwquality)
  ansible.builtin.import_tasks: auth.yml
  tags: [auth]

- name: Include ssh hardening
  ansible.builtin.import_tasks: ssh.yml
  tags: [ssh]

- name: Include kernel/sysctl tasks
  ansible.builtin.import_tasks: sysctl.yml
  tags: [sysctl]

- name: Include services (auditd, rsyslog, ufw)
  ansible.builtin.import_tasks: services.yml
  tags: [services]

- name: Include audit summary
  ansible.builtin.import_tasks: audit.yml
  tags: [audit]
