---
- name: Install baseline packages (pwquality, auditd, ufw, rsyslog, unattended-upgrades)
  ansible.builtin.apt:
    name: "{{ cis_packages }}"
    state: present
    update_cache: yes
  when: cis_mode == 'enforce'

- name: Audit baseline packages presence
  ansible.builtin.package_facts:
    manager: auto

- name: Record missing baseline packages (audit)
  ansible.builtin.set_fact:
    cis_audit_missing_packages: >-
      {{
        cis_packages
        | reject('in', (ansible_facts.packages.keys() | list))
        | list
      }}
  when: cis_mode == 'audit'
