---
# I think this is better code hygin but also a idempotence automation killer!
#- name: Check if legacy drop-in exists
#  ansible.builtin.stat:
#    path: /etc/ssh/sshd_config.d/*ansible*
#  register: _old_dropin

#- name: Remove legacy drop-in
#  ansible.builtin.file:
#    path: "{{ _old_dropin.stat.path }}"
#    state: absent
#  when: _old_dropin.stat.exists

# Changes when file content is actually modified
- name: Template hardened sshd drop-in
  ansible.builtin.template:
    src: sshd_10-ansible.conf.j2
    dest: /etc/ssh/sshd_config.d/10-ansible.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload sshd

# Audit
# Get effective sshd config (resolve conditionals with -C)
- name: Audit sshd effective settings
  ansible.builtin.command: >
    sshd -T
    -C user=root
    -C host={{ ansible_facts.fqdn | default('localhost') }}
    -C addr=127.0.0.1
  register: _sshd_t
  changed_when: false

# Normalize to a simple lowercase list (no filtering so it never comes back empty)
- name: Normalize sshd audit lines for report
  ansible.builtin.set_fact:
    _sshd: "{{ _sshd_t.stdout | trim | split('\n') | map('lower') | list }}"
  changed_when: false
