---
- name: Ensure ASLR is enabled
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: "2"
    state: present
    reload: yes
  when: cis_mode == 'enforce'

- name: Restrict core dumps
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: "0"
    state: present
    reload: yes
  when: cis_mode == 'enforce'

- name: Restrict ptrace_scope
  ansible.posix.sysctl:
    name: kernel.yama.ptrace_scope
    value: "1"
    state: present
    reload: yes
  when: cis_mode == 'enforce'

- name: Audit kernel/sysctl hardening
  ansible.builtin.command: >
    sysctl kernel.randomize_va_space fs.suid_dumpable kernel.yama.ptrace_scope
  register: _sysctl
  changed_when: false
